title: TEDxWarwick
permalink: /:title


#############
# Renderers #
#############

markdown: kramdown

kramdown:
  auto_ids: false
  parse_block_html: true

sass:
  style: compressed

plugins:
  - jekyll-sitemap

error_mode: strict
strict_variables: true
strict_filters: true


#########
# Files #
#########

collections_dir: _collections

collections:
  events:
    output: true
  forms:
    output: true
  partners:
    output: false
  recruitment:
    output: true
    permalink: /get-involved/:name
  speakers:
    output: false


defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
      nav: events

  - scope:
      path: ""
      type: forms
    values:
      layout: form

  - scope:
      path: ""
      type: recruitment
    values:
      layout: recruitment
      nav: recruitment

  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - LICENSE
  - README.md
  - CNAME
  - docs/


###################
# Site parameters #
###################

url: https://neo.tedxwarwick.com

nav:
  - key: events
    name: "Events"
    page: "/events"
  - key: partners
    name: "Partners"
    page: "/partners"
  - key: recruitment
    name: "Get Involved"
    page: "/get-involved"
  - key: about
    name: "About"
    page: "/about"

cta:

fb-app-id: "600131706999745"
fb-page: "TEDxWarwick"
twitter-handle: "TEDxWarwick"

repo: "TEDxWarwickTechnical/tedxwarwicktechnical.github.io"
